services:

  postgres:
    image: postgres:17
    container_name: postgres-contracheque
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contracheque
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - automacoes

  redis:
    image: redis:7-alpine
    container_name: redis-contracheque
    restart: unless-stopped
    networks:
      - automacoes

  backend:
    image: contracheque-bot-backend:latest
    container_name: contracheque-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/contracheque
      REDIS_URL: redis://redis:6379
      PORT: 3001
    ports:
      - "3001:3001"
      - "5555:5555"
    networks:
      - automacoes

  worker:
    image: contracheque-bot-worker:latest
    container_name: contracheque-worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/contracheque
      REDIS_URL: redis://redis:6379
    networks:
      - automacoes

  frontend:
    image: contracheque-bot-frontend:latest
    container_name: contracheque-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - automacoes

networks:
  automacoes:
    driver: bridge

volumes:
  pgdata:
