const STATUS = {
    PROCESSADO: 'PROCESSADO',
    PENDENTE: 'PENDENTE',
    PROCESSANDO: 'PROCESSANDO',
    REENVIANDO: 'REENVIANDO',
    ENVIADO: 'ENVIADO',
    ERRO: 'ERRO',
    ERRO_ENVIO: 'ERRO_ENVIO',
    ERRO_PDF: 'ERRO_PDF',
    SEM_TELEFONE: 'SEM_TELEFONE',
    FUNCIONARIO_NAO_ENCONTRADO: 'FUNCIONARIO_NAO_ENCONTRADO',
    NOME_DIVERGENTE: 'NOME_DIVERGENTE',
    DUPLICADO_HASH: 'DUPLICADO_HASH',
    DUPLICADO_COMPETENCIA: 'DUPLICADO_COMPETENCIA',
    PROCESSANDOFINALIZADOCANCELADO: 'PROCESSANDOFINALIZADOCANCELADO',
};

module.exports = STATUS;
module.exports.STATUS = STATUS;
